version: 2

updates:
  - package-ecosystem: nuget
    directory: /src/ClipPort
    schedule:
      interval: weekly
    groups:
      clipport-runtime:
        patterns:
          - "*"
    open-pull-requests-limit: 5

  - package-ecosystem: nuget
    directory: /tests/ClipPort.CoreTests
    schedule:
      interval: weekly
    groups:
      clipport-tests:
        patterns:
          - "*"
    open-pull-requests-limit: 5

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      github-actions:
        patterns:
          - "*"
    open-pull-requests-limit: 5
